/**********************************************************************************************************************
 * @file        main.c
 * @brief       Basic STM32CubeIDE example for the STM32 UART Logger library.
 * @details     Shows where to initialize and use drivers/uart_logger in a CubeMX generated STM32 HAL project.
 * @author      Satish Kanawade
 * @date        20-May-2026
 * @version     1.0.0
 * @copyright : Satish Kanawade. All rights reserved.
 *********************************************************************************************************************/

#include "main.h"
#include "usart.h"
#include "gpio.h"
#include "stm32_uart_logger.h"

static STM32_UART_Logger_Handle_t debugLogger;

void SystemClock_Config(void);
static void App_UARTLogger_Init(void);
static void App_UARTLogger_Task(void);

// Main application entry point generated by STM32CubeIDE with logger integration added.
int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_USART2_UART_Init();

    App_UARTLogger_Init();

    STM32_LOG_INFO(&debugLogger, "UART logger example started");
    STM32_LOG_INFO(&debugLogger, "Library version: 1.0.0");
    STM32_LOG_DEBUG(&debugLogger, "Build: %s %s", __DATE__, __TIME__);

    while (1)
    {
        App_UARTLogger_Task();
        HAL_Delay(1000U);
    }
}

// Initializes the UART logger library after CubeMX initializes the UART peripheral.
static void App_UARTLogger_Init(void)
{
    STM32_UART_Logger_Config_t loggerConfig = {
        .huart = &huart2,
        .txTimeoutMs = 100U,
        .minimumLevel = STM32_UART_LOGGER_LEVEL_DEBUG,
        .enableTimestamp = 1U,
        .enableLevelPrefix = 1U,
        .lineEnding = "\r\n"
    };

    if (STM32_UART_Logger_Init(&debugLogger, &loggerConfig) != STM32_UART_LOGGER_OK)
    {
        Error_Handler();
    }
}

// Sends one periodic log line from the application loop.
static void App_UARTLogger_Task(void)
{
    static uint32_t counter = 0U;

    counter++;
    STM32_LOG_INFO(&debugLogger, "Heartbeat: %lu, Tick: %lu ms",
                   (unsigned long)counter,
                   (unsigned long)HAL_GetTick());
}

/*
 * Keep the CubeMX generated SystemClock_Config function in your real project.
 * This example only shows where the logger code is placed.
 */
